#!/usr/bin/python
# -*- coding: utf-8 -*-

en_ocean_keywords = [
	u'atmosphere',
	u'climate change',
	u'coral',
	u'CO2',
	u'crustaceans',
	u'El Niño',
	u'global temperature',
	u'Great Barrier Reef',
	u'greenhouse gas',
	u'Indian Ocean',
	u'oceanographer',
	u'oceanography',
	u'Pacific Ocean',
	u'sea temperature',
	u'Submarine Canyon',
	u'storm', 
	u'zooxanthellae',
]

pt_ocean_keywords = [
	u'algas',
	u'atmofera',
	u'clima',
	u'mudança climática',
	u'corais',
	u'CO2',
	u'dessalinização',
	u'El Niño',
	u'gás carbônico',
	u'impacto ambiental',
	u'mananciais subterrâneos',
	u'meio ambiente',
	u'mudança do clima',
	u'mudança climática',
	u'oceano',
	u'oceanos',
	u'plâncton',
	u'praia',
	u'unidades de conservação',
	u'zona costeira',
]
